
# Handle React Router's client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specifically handle direct navigation to /ConfirmEmail
[[redirects]]
  from = "/ConfirmEmail"
  to = "/confirm-email"
  status = 301
